source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.0"

pod 'AFNetworking', '~> 3.0'
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.8.1'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'Masonry', '~> 1.0.1'

target 'BuDeJie' do
  # pod 'Kiwi'
end
